export const copy = {
  homeTitle: 'Dormia',
  homeIntro:
    '“为那些宏大的、混乱的、脆弱的、怕被批判的灵感，提供一个安全的、不带期待的、无需产出的安息之地”',
  submitSuccess: '灵感已安放',
  submitError: '安放失败，请稍后重试',
  emptyDepths: '这里还很安静。',
  deleteHint: '选择忘记',
  inputPlaceholder: '……',
  inputAriaLabel: '输入你的念头',
  submitLabel: '沉入',
  submitAriaLabel: '放入深处',
  navHome: '归处',
  navDepths: '深处',
  navAriaLabel: '页面切换',
  closeAriaLabel: '关闭',
  homeCtaLabel: '沉入',
  composeTitle: '安放灵感',
  composeInputAriaLabel: '输入新的灵感',
  composeCloseAriaLabel: '关闭安放卡片',
  composeInputPlaceholder: '把想法轻轻放进这里……',
  composeSubmitLabel: '确认安放',
  composeCancelLabel: '取消',
  recordBackLabel: '返回',
  commentOpenLabel: '增加附言',
  commentSheetTitle: '新增附言',
  commentInputAriaLabel: '新增评论',
  commentInputPlaceholder: '给这个念头留一句附言……',
  commentAddLabel: '提交',
  commentsTitle: '附言',
  commentsEmpty: '当前没有附言',
} as const;
